version: "3"

services:
    server:
        build: backend/
        container_name: financer-server
        restart: always
        ports:
            - 3000:3000

    client:
        build:
            context: .
            args:
                REACT_APP_SERVER_URL: http://localhost:3000
        container_name: financer-client
        restart: always
        ports:
            - 8080:80
        links:
            - server
