version: '3'

services:
  mysql:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - financer-volume
  financer-server:
    image: raphaelmue/financer:latest
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql

volumes:
  financer_volume:
    external: false