version: "3"

services:
    server:
        image: raphaelmue/financer-server:latest
        container_name: financer-server
        restart: always
        ports:
            - 3000:3000

    client:
        image: raphaelmue/financer-client
        container_name: financer-client
        restart: always
        ports:
            - 8080:80
        links:
            - server
        environment:
            REACT_APP_SERVER_URL: http://financer-server:3001
