name: CI Pipeline for Backend

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

defaults:
    run:
        working-directory: ./backend

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3
            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'oracle'
                    cache: maven

            -   name: Build Backend with Maven
                run: mvn clean install -DskipTests

            -   name: Execute all tests
                run: mvn test

            -   name: Publish Test Report
                if: success() || failure()
                uses: scacap/action-surefire-report@v1